spring.application.name=aerolink

management.server.port=8081
management.endpoints.web.base-path=/
management.endpoints.web.path-mapping.health=status
management.endpoints.web.exposure.include=health,info,prometheus
management.info.env.enabled=true
management.metrics.enable.jvm=true
management.metrics.enable.process=true
management.metrics.enable.http.server.requests=true
management.metrics.enable.http.client.requests=true

info.dependencies.resilience4j=@resilience4j.version@
info.dependencies.bucket4j=@bucket4j.version@
info.dependencies.logstash-logback-encoder=@logstash-logback-encoder.version@

aviation.provider.api.base-url=https://aviationweather.gov/api/data
aviation.provider.api.connect-timeout=5s
aviation.provider.api.read-timeout=10s
aviation.provider.api.max-total-connections=50
aviation.provider.api.max-connections-per-route=20
aviation.provider.api.request-limit-per-minute=60


aerolink.provider=aviationWeather