spring.application.name=aerolink

aviation.provider.api.base-url=https://aviationweather.gov/api/data
aviation.provider.api.connect-timeout=5s
aviation.provider.api.read-timeout=10s
aviation.provider.api.max-total-connections=50
aviation.provider.api.max-connections-per-route=20
aviation.provider.api.request-limit-per-minute=60
